### ISSUE TITLE
Jesus Danery Lazo López mapa mental 

### ISSUE THREAD

**Issue by Dasus2332** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Dasus2332#3]
[Jesus Danery Lazo López mapa conceptual .pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Dasus2332/files/9748014/Jesus.Danery.Lazo.Lopez.mapa.conceptual.pdf)

**Comment by josealfredo79** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Revisado
